from sqlalchemy import create_engine, event, inspect, text
from sqlalchemy.orm import DeclarativeBase, sessionmaker

from .config import settings
from .inventory_constants import DEFAULT_INVENTORY_SECRETARIAT, DEFAULT_INVENTORY_SECTOR
from .inventory_service import normalize_catalog_name

database_url = settings.effective_database_url
connect_args = {"check_same_thread": False} if database_url.startswith("sqlite") else {}
engine = create_engine(database_url, pool_pre_ping=True, connect_args=connect_args)


if database_url.startswith("sqlite"):
    @event.listens_for(engine, "connect")
    def _enable_sqlite_foreign_keys(dbapi_connection, _connection_record) -> None:
        cursor = dbapi_connection.cursor()
        cursor.execute("PRAGMA foreign_keys=ON")
        cursor.close()


SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False, expire_on_commit=False)


class Base(DeclarativeBase):
    pass


def ensure_schema_compatibility() -> None:
    inspector = inspect(engine)
    table_names = inspector.get_table_names()
    if "users" not in table_names:
        return
    user_columns = {column["name"] for column in inspector.get_columns("users")}
    with engine.begin() as connection:
        if "email_verified_at" not in user_columns:
            connection.execute(text("ALTER TABLE users ADD COLUMN email_verified_at TIMESTAMP"))
            connection.execute(
                text(
                    """
                    UPDATE users
                    SET email_verified_at = COALESCE(created_at, CURRENT_TIMESTAMP)
                    WHERE lower(email) LIKE '%@%.cabofrio.rj.gov.br'
                      AND lower(email) NOT LIKE '%@cabofrio.rj.gov.br'
                    """
                )
            )
        if "email_verification_token_hash" not in user_columns:
            connection.execute(text("ALTER TABLE users ADD COLUMN email_verification_token_hash VARCHAR(128) DEFAULT ''"))
        if "email_verification_expires_at" not in user_columns:
            connection.execute(text("ALTER TABLE users ADD COLUMN email_verification_expires_at TIMESTAMP"))
        if "password_reset_token_hash" not in user_columns:
            connection.execute(text("ALTER TABLE users ADD COLUMN password_reset_token_hash VARCHAR(128) DEFAULT ''"))
        if "password_reset_expires_at" not in user_columns:
            connection.execute(text("ALTER TABLE users ADD COLUMN password_reset_expires_at TIMESTAMP"))
        if "registration" not in user_columns:
            connection.execute(text("ALTER TABLE users ADD COLUMN registration VARCHAR(80) DEFAULT ''"))
        if "department_sector_id" not in user_columns:
            connection.execute(text("ALTER TABLE users ADD COLUMN department_sector_id INTEGER"))
        if "role" in user_columns:
            connection.execute(text("UPDATE users SET role = 'technician' WHERE role = 'helpdesk'"))
            connection.execute(text("UPDATE users SET role = 'user' WHERE role = 'requester'"))

    if "role_configs" in table_names:
        with engine.begin() as connection:
            connection.execute(
                text(
                    """
                    UPDATE role_configs
                    SET role = 'technician', label = 'Técnico'
                    WHERE role = 'helpdesk'
                      AND NOT EXISTS (SELECT 1 FROM role_configs WHERE role = 'technician')
                    """
                )
            )
            connection.execute(text("DELETE FROM role_configs WHERE role IN ('helpdesk', 'requester')"))

    if "inventory_sectors" in table_names and "inventory_secretariats" not in table_names:
        secretariat_id_column = (
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if engine.dialect.name == "postgresql"
            else "id INTEGER PRIMARY KEY"
        )
        with engine.begin() as connection:
            connection.execute(
                text(
                    f"""
                    CREATE TABLE inventory_secretariats (
                        {secretariat_id_column},
                        name VARCHAR(160) NOT NULL,
                        normalized_name VARCHAR(180) NOT NULL UNIQUE,
                        is_active BOOLEAN DEFAULT TRUE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
            )
            connection.execute(text("CREATE INDEX ix_inventory_secretariats_name ON inventory_secretariats (name)"))
            connection.execute(text("CREATE INDEX ix_inventory_secretariats_normalized_name ON inventory_secretariats (normalized_name)"))
            connection.execute(text("CREATE INDEX ix_inventory_secretariats_is_active ON inventory_secretariats (is_active)"))

    if "inventory_sectors" in table_names:
        sector_columns = {column["name"] for column in inspector.get_columns("inventory_sectors")}
        normalized_default_sector = normalize_catalog_name(DEFAULT_INVENTORY_SECTOR)
        normalized_default_secretariat = normalize_catalog_name(DEFAULT_INVENTORY_SECRETARIAT)
        with engine.begin() as connection:
            if "secretariat_id" not in sector_columns:
                connection.execute(text("ALTER TABLE inventory_sectors ADD COLUMN secretariat_id INTEGER"))
            connection.execute(
                text(
                    """
                    INSERT INTO inventory_secretariats (name, normalized_name, is_active, created_at, updated_at)
                    SELECT CAST(:name AS VARCHAR), CAST(:normalized_name AS VARCHAR), TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                    WHERE NOT EXISTS (
                        SELECT 1 FROM inventory_secretariats WHERE normalized_name = CAST(:normalized_name AS VARCHAR)
                    )
                    """
                ),
                {"name": DEFAULT_INVENTORY_SECRETARIAT, "normalized_name": normalized_default_secretariat},
            )
            connection.execute(
                text(
                    """
                    INSERT INTO inventory_sectors (name, normalized_name, is_active, created_at, updated_at)
                    SELECT CAST(:name AS VARCHAR), CAST(:normalized_name AS VARCHAR), TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                    WHERE NOT EXISTS (
                        SELECT 1 FROM inventory_sectors WHERE normalized_name = CAST(:normalized_name AS VARCHAR)
                    )
                    """
                ),
                {"name": DEFAULT_INVENTORY_SECTOR, "normalized_name": normalized_default_sector},
            )
            connection.execute(
                text(
                    """
                    UPDATE inventory_sectors
                    SET secretariat_id = (
                        SELECT id FROM inventory_secretariats
                        WHERE normalized_name = CAST(:secretariat_name AS VARCHAR)
                        LIMIT 1
                    )
                    WHERE secretariat_id IS NULL
                      AND normalized_name = CAST(:sector_name AS VARCHAR)
                    """
                ),
                {
                    "secretariat_name": normalized_default_secretariat,
                    "sector_name": normalized_default_sector,
                },
            )

    if "assets" in table_names:
        asset_columns = {column["name"] for column in inspector.get_columns("assets")}
        with engine.begin() as connection:
            if "specifications" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN specifications TEXT DEFAULT ''"))
            if "supplier_id" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN supplier_id INTEGER"))
            if "equipment_type_id" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN equipment_type_id INTEGER"))
            if "manufacturer_id" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN manufacturer_id INTEGER"))
            if "equipment_model_id" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN equipment_model_id INTEGER"))
            if "sector_id" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN sector_id INTEGER"))
            if "received_at" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN received_at TIMESTAMP"))
            if "delivered_at" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN delivered_at TIMESTAMP"))
            if "notes" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN notes TEXT DEFAULT ''"))
            if "retired_at" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN retired_at TIMESTAMP"))
            if "retired_by_user_id" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN retired_by_user_id INTEGER"))
            if "retirement_reason" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN retirement_reason VARCHAR(60) DEFAULT ''"))
            if "retirement_justification" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN retirement_justification TEXT DEFAULT ''"))
            if "retirement_notes" not in asset_columns:
                connection.execute(text("ALTER TABLE assets ADD COLUMN retirement_notes TEXT DEFAULT ''"))
            if "asset_movements" not in table_names:
                movement_id_column = (
                    "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                    if engine.dialect.name == "postgresql"
                    else "id INTEGER PRIMARY KEY"
                )
                connection.execute(
                    text(
                        f"""
                        CREATE TABLE asset_movements (
                            {movement_id_column},
                            asset_id INTEGER NOT NULL,
                            action VARCHAR(60) NOT NULL,
                            from_sector_id INTEGER,
                            to_sector_id INTEGER,
                            from_user_id INTEGER,
                            to_user_id INTEGER,
                            from_status VARCHAR(40),
                            to_status VARCHAR(40) NOT NULL,
                            movement_date TIMESTAMP NOT NULL,
                            notes TEXT DEFAULT '',
                            actor_id INTEGER,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            FOREIGN KEY(asset_id) REFERENCES assets(id),
                            FOREIGN KEY(from_sector_id) REFERENCES inventory_sectors(id),
                            FOREIGN KEY(to_sector_id) REFERENCES inventory_sectors(id),
                            FOREIGN KEY(from_user_id) REFERENCES users(id),
                            FOREIGN KEY(to_user_id) REFERENCES users(id),
                            FOREIGN KEY(actor_id) REFERENCES users(id)
                        )
                        """
                    )
                )
                connection.execute(text("CREATE INDEX ix_asset_movements_asset_id ON asset_movements (asset_id)"))
                connection.execute(text("CREATE INDEX ix_asset_movements_action ON asset_movements (action)"))
                connection.execute(text("CREATE INDEX ix_asset_movements_actor_id ON asset_movements (actor_id)"))
                connection.execute(text("CREATE INDEX ix_asset_movements_created_at ON asset_movements (created_at)"))
                connection.execute(text("CREATE INDEX ix_asset_movements_movement_date ON asset_movements (movement_date)"))

    if "inventory_suppliers" in table_names and "inventory_contracts" not in table_names:
        contract_id_column = (
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if engine.dialect.name == "postgresql"
            else "id INTEGER PRIMARY KEY"
        )
        with engine.begin() as connection:
            connection.execute(
                text(
                    f"""
                    CREATE TABLE inventory_contracts (
                        {contract_id_column},
                        name VARCHAR(180) NOT NULL,
                        normalized_name VARCHAR(220) NOT NULL UNIQUE,
                        supplier_id INTEGER NOT NULL,
                        is_active BOOLEAN DEFAULT TRUE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        FOREIGN KEY(supplier_id) REFERENCES inventory_suppliers(id)
                    )
                    """
                )
            )
            connection.execute(text("CREATE INDEX ix_inventory_contracts_name ON inventory_contracts (name)"))
            connection.execute(text("CREATE INDEX ix_inventory_contracts_normalized_name ON inventory_contracts (normalized_name)"))
            connection.execute(text("CREATE INDEX ix_inventory_contracts_supplier_id ON inventory_contracts (supplier_id)"))
            connection.execute(text("CREATE INDEX ix_inventory_contracts_is_active ON inventory_contracts (is_active)"))

    if "inventory_delivery_terms" in table_names:
        term_columns = {column["name"] for column in inspector.get_columns("inventory_delivery_terms")}
        with engine.begin() as connection:
            if "contract_id" not in term_columns:
                connection.execute(text("ALTER TABLE inventory_delivery_terms ADD COLUMN contract_id INTEGER"))

    if "tickets" not in table_names:
        return
    ticket_columns = {column["name"] for column in inspector.get_columns("tickets")}
    with engine.begin() as connection:
        if "form_data" not in ticket_columns:
            connection.execute(text("ALTER TABLE tickets ADD COLUMN form_data JSON"))
        if "form_schema_snapshot" not in ticket_columns:
            connection.execute(text("ALTER TABLE tickets ADD COLUMN form_schema_snapshot JSON"))
        if "service_id" not in ticket_columns:
            connection.execute(text("ALTER TABLE tickets ADD COLUMN service_id INTEGER"))


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
