"""baseline schema

Revision ID: 20260717_0001
Revises:
Create Date: 2026-07-17 17:14:40.789959+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '20260717_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_equipment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_equipment_types_is_active'), 'inventory_equipment_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_inventory_equipment_types_name'), 'inventory_equipment_types', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_equipment_types_normalized_name'), 'inventory_equipment_types', ['normalized_name'], unique=True)
    op.create_table('inventory_manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_manufacturers_is_active'), 'inventory_manufacturers', ['is_active'], unique=False)
    op.create_index(op.f('ix_inventory_manufacturers_name'), 'inventory_manufacturers', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_manufacturers_normalized_name'), 'inventory_manufacturers', ['normalized_name'], unique=True)
    op.create_table('inventory_secretariats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_secretariats_is_active'), 'inventory_secretariats', ['is_active'], unique=False)
    op.create_index(op.f('ix_inventory_secretariats_name'), 'inventory_secretariats', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_secretariats_normalized_name'), 'inventory_secretariats', ['normalized_name'], unique=True)
    op.create_table('inventory_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_suppliers_is_active'), 'inventory_suppliers', ['is_active'], unique=False)
    op.create_index(op.f('ix_inventory_suppliers_name'), 'inventory_suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_suppliers_normalized_name'), 'inventory_suppliers', ['normalized_name'], unique=True)
    op.create_table('role_configs',
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('ldap_group', sa.String(length=180), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('service_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('form_schema', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_catalog_category'), 'service_catalog', ['category'], unique=False)
    op.create_index(op.f('ix_service_catalog_name'), 'service_catalog', ['name'], unique=False)
    op.create_table('inventory_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('normalized_name', sa.String(length=220), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['inventory_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_contracts_is_active'), 'inventory_contracts', ['is_active'], unique=False)
    op.create_index(op.f('ix_inventory_contracts_name'), 'inventory_contracts', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_contracts_normalized_name'), 'inventory_contracts', ['normalized_name'], unique=True)
    op.create_index(op.f('ix_inventory_contracts_supplier_id'), 'inventory_contracts', ['supplier_id'], unique=False)
    op.create_table('inventory_equipment_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['inventory_equipment_types.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['inventory_manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_inventory_equipment_models_normalized_name')
    )
    op.create_index(op.f('ix_inventory_equipment_models_equipment_type_id'), 'inventory_equipment_models', ['equipment_type_id'], unique=False)
    op.create_index(op.f('ix_inventory_equipment_models_is_active'), 'inventory_equipment_models', ['is_active'], unique=False)
    op.create_index(op.f('ix_inventory_equipment_models_manufacturer_id'), 'inventory_equipment_models', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_inventory_equipment_models_name'), 'inventory_equipment_models', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_equipment_models_normalized_name'), 'inventory_equipment_models', ['normalized_name'], unique=False)
    op.create_table('inventory_sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('secretariat_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['secretariat_id'], ['inventory_secretariats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_sectors_is_active'), 'inventory_sectors', ['is_active'], unique=False)
    op.create_index(op.f('ix_inventory_sectors_name'), 'inventory_sectors', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_sectors_normalized_name'), 'inventory_sectors', ['normalized_name'], unique=True)
    op.create_index(op.f('ix_inventory_sectors_secretariat_id'), 'inventory_sectors', ['secretariat_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('secretariat', sa.String(length=150), nullable=False),
    sa.Column('department_sector_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('registration', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verification_token_hash', sa.String(length=128), nullable=False),
    sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token_hash', sa.String(length=128), nullable=False),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_sector_id'], ['inventory_sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('asset_type', sa.String(length=60), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=140), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=False),
    sa.Column('specifications', sa.Text(), nullable=False),
    sa.Column('patrimony', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('ip_address', sa.String(length=60), nullable=False),
    sa.Column('operating_system', sa.String(length=120), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('equipment_type_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('equipment_model_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_by_user_id', sa.Integer(), nullable=True),
    sa.Column('retirement_reason', sa.String(length=60), nullable=False),
    sa.Column('retirement_justification', sa.Text(), nullable=False),
    sa.Column('retirement_notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_model_id'], ['inventory_equipment_models.id'], ),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['inventory_equipment_types.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['inventory_manufacturers.id'], ),
    sa.ForeignKeyConstraint(['retired_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['inventory_sectors.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['inventory_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('inventory_delivery_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_number', sa.String(length=40), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('contract_number', sa.String(length=120), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destination_sector_id', sa.Integer(), nullable=False),
    sa.Column('destination_unit', sa.String(length=180), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=180), nullable=False),
    sa.Column('recipient_email', sa.String(length=180), nullable=False),
    sa.Column('recipient_registration', sa.String(length=80), nullable=False),
    sa.Column('recipient_phone', sa.String(length=40), nullable=False),
    sa.Column('adcetei_signer_name', sa.String(length=180), nullable=False),
    sa.Column('adcetei_signer_title', sa.String(length=180), nullable=False),
    sa.Column('item_observation', sa.String(length=180), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delivered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['inventory_contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivered_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_sector_id'], ['inventory_sectors.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_delivery_terms_contract_id'), 'inventory_delivery_terms', ['contract_id'], unique=False)
    op.create_index(op.f('ix_inventory_delivery_terms_created_at'), 'inventory_delivery_terms', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_delivery_terms_destination_sector_id'), 'inventory_delivery_terms', ['destination_sector_id'], unique=False)
    op.create_index(op.f('ix_inventory_delivery_terms_recipient_user_id'), 'inventory_delivery_terms', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_inventory_delivery_terms_status'), 'inventory_delivery_terms', ['status'], unique=False)
    op.create_index(op.f('ix_inventory_delivery_terms_term_number'), 'inventory_delivery_terms', ['term_number'], unique=True)
    op.create_table('asset_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('from_sector_id', sa.Integer(), nullable=True),
    sa.Column('to_sector_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=False),
    sa.Column('movement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['from_sector_id'], ['inventory_sectors.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_sector_id'], ['inventory_sectors.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_movements_action'), 'asset_movements', ['action'], unique=False)
    op.create_index(op.f('ix_asset_movements_actor_id'), 'asset_movements', ['actor_id'], unique=False)
    op.create_index(op.f('ix_asset_movements_asset_id'), 'asset_movements', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_movements_created_at'), 'asset_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_asset_movements_movement_date'), 'asset_movements', ['movement_date'], unique=False)
    op.create_table('inventory_delivery_term_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=80), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=False),
    sa.Column('specification', sa.Text(), nullable=False),
    sa.Column('observation', sa.String(length=180), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['inventory_delivery_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_delivery_term_items_asset_id'), 'inventory_delivery_term_items', ['asset_id'], unique=False)
    op.create_index(op.f('ix_inventory_delivery_term_items_term_id'), 'inventory_delivery_term_items', ['term_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('urgency', sa.String(length=30), nullable=False),
    sa.Column('impact', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=False),
    sa.Column('origin', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('form_schema_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assignee_id'), 'tickets', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tickets_category'), 'tickets', ['category'], unique=False)
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_requester_id'), 'tickets', ['requester_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_title'), 'tickets', ['title'], unique=False)
    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('internal', sa.Boolean(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_comments_ticket_id'), 'ticket_comments', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_comments_ticket_id'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index(op.f('ix_tickets_title'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_requester_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assignee_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_inventory_delivery_term_items_term_id'), table_name='inventory_delivery_term_items')
    op.drop_index(op.f('ix_inventory_delivery_term_items_asset_id'), table_name='inventory_delivery_term_items')
    op.drop_table('inventory_delivery_term_items')
    op.drop_index(op.f('ix_asset_movements_movement_date'), table_name='asset_movements')
    op.drop_index(op.f('ix_asset_movements_created_at'), table_name='asset_movements')
    op.drop_index(op.f('ix_asset_movements_asset_id'), table_name='asset_movements')
    op.drop_index(op.f('ix_asset_movements_actor_id'), table_name='asset_movements')
    op.drop_index(op.f('ix_asset_movements_action'), table_name='asset_movements')
    op.drop_table('asset_movements')
    op.drop_index(op.f('ix_inventory_delivery_terms_term_number'), table_name='inventory_delivery_terms')
    op.drop_index(op.f('ix_inventory_delivery_terms_status'), table_name='inventory_delivery_terms')
    op.drop_index(op.f('ix_inventory_delivery_terms_recipient_user_id'), table_name='inventory_delivery_terms')
    op.drop_index(op.f('ix_inventory_delivery_terms_destination_sector_id'), table_name='inventory_delivery_terms')
    op.drop_index(op.f('ix_inventory_delivery_terms_created_at'), table_name='inventory_delivery_terms')
    op.drop_index(op.f('ix_inventory_delivery_terms_contract_id'), table_name='inventory_delivery_terms')
    op.drop_table('inventory_delivery_terms')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_inventory_sectors_secretariat_id'), table_name='inventory_sectors')
    op.drop_index(op.f('ix_inventory_sectors_normalized_name'), table_name='inventory_sectors')
    op.drop_index(op.f('ix_inventory_sectors_name'), table_name='inventory_sectors')
    op.drop_index(op.f('ix_inventory_sectors_is_active'), table_name='inventory_sectors')
    op.drop_table('inventory_sectors')
    op.drop_index(op.f('ix_inventory_equipment_models_normalized_name'), table_name='inventory_equipment_models')
    op.drop_index(op.f('ix_inventory_equipment_models_name'), table_name='inventory_equipment_models')
    op.drop_index(op.f('ix_inventory_equipment_models_manufacturer_id'), table_name='inventory_equipment_models')
    op.drop_index(op.f('ix_inventory_equipment_models_is_active'), table_name='inventory_equipment_models')
    op.drop_index(op.f('ix_inventory_equipment_models_equipment_type_id'), table_name='inventory_equipment_models')
    op.drop_table('inventory_equipment_models')
    op.drop_index(op.f('ix_inventory_contracts_supplier_id'), table_name='inventory_contracts')
    op.drop_index(op.f('ix_inventory_contracts_normalized_name'), table_name='inventory_contracts')
    op.drop_index(op.f('ix_inventory_contracts_name'), table_name='inventory_contracts')
    op.drop_index(op.f('ix_inventory_contracts_is_active'), table_name='inventory_contracts')
    op.drop_table('inventory_contracts')
    op.drop_index(op.f('ix_service_catalog_name'), table_name='service_catalog')
    op.drop_index(op.f('ix_service_catalog_category'), table_name='service_catalog')
    op.drop_table('service_catalog')
    op.drop_table('role_configs')
    op.drop_index(op.f('ix_inventory_suppliers_normalized_name'), table_name='inventory_suppliers')
    op.drop_index(op.f('ix_inventory_suppliers_name'), table_name='inventory_suppliers')
    op.drop_index(op.f('ix_inventory_suppliers_is_active'), table_name='inventory_suppliers')
    op.drop_table('inventory_suppliers')
    op.drop_index(op.f('ix_inventory_secretariats_normalized_name'), table_name='inventory_secretariats')
    op.drop_index(op.f('ix_inventory_secretariats_name'), table_name='inventory_secretariats')
    op.drop_index(op.f('ix_inventory_secretariats_is_active'), table_name='inventory_secretariats')
    op.drop_table('inventory_secretariats')
    op.drop_index(op.f('ix_inventory_manufacturers_normalized_name'), table_name='inventory_manufacturers')
    op.drop_index(op.f('ix_inventory_manufacturers_name'), table_name='inventory_manufacturers')
    op.drop_index(op.f('ix_inventory_manufacturers_is_active'), table_name='inventory_manufacturers')
    op.drop_table('inventory_manufacturers')
    op.drop_index(op.f('ix_inventory_equipment_types_normalized_name'), table_name='inventory_equipment_types')
    op.drop_index(op.f('ix_inventory_equipment_types_name'), table_name='inventory_equipment_types')
    op.drop_index(op.f('ix_inventory_equipment_types_is_active'), table_name='inventory_equipment_types')
    op.drop_table('inventory_equipment_types')
    # ### end Alembic commands ###
